MOVIEBOOKIE/MOVIEBOOKIE_BE

- .github/workflows/moviebookie-cd.yml
- .github/workflows/moviebookie-ci.yml
- Dockerfile
> [INIT] CI / CD 구축

- .gitmodules
- build.gradle
- src/main/java/project/luckybooky/domain/user/AuthenticatedUserUtils.java
- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/converter/AuthConverter.java
- src/main/java/project/luckybooky/domain/user/converter/UserConverter.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserResponseDTO.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/repository/UserRepository.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/domain/user/util/AuthenticatedUserUtils.java
- src/main/java/project/luckybooky/global/apiPayload/common/BaseEntity.java
- src/main/java/project/luckybooky/global/apiPayload/common/BaseResponse.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- src/main/java/project/luckybooky/global/apiPayload/response/ResultCode.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/config/SwaggerConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
- src/main/java/project/luckybooky/global/jwt/JwtAuthenticationToken.java
- src/main/java/project/luckybooky/global/jwt/JwtUtil.java
- src/main/java/project/luckybooky/global/oauth/dto/KakaoDTO.java
- src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
- src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/project/luckybooky/global/oauth/util/CookieUtil.java
- src/main/java/project/luckybooky/global/oauth/util/KakaoUtil.java
- #5  
- 카카오 소셜 로그인 기능 구현
- 유저 정보 조회
- 로그아웃 기능
> [feat] 카카오 소셜 로그인, 유저 정보 조회, 로그아웃 기능 구현

- Dockerfile
- build.gradle
- #7 
- 기존 jdk 17 -> 21 버전으로 변경하였습니다 .
> [SETTING] jdk 버전 변경 (17 -> 21)

- src/main/java/project/luckybooky/domain/user/entity/ContentCategory.java
- src/main/java/project/luckybooky/domain/user/entity/GroupType.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/entity/UserType.java
- src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
- #14 
- 사용자 유형 조사 관련 enum 세팅
- 유저 테이블 컬럼 값 추가
- 유저 더미데이터 생성
> [INIT] user 도메인 세팅 + 유저 더미데이터 생성

- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
- src/main/java/project/luckybooky/domain/user/converter/UserConverter.java
- src/main/java/project/luckybooky/domain/user/dto/request/UserTypeAssignRequest.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserResponseDTO.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserTypeAssignResponse.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserTypeResultDTO.java
- src/main/java/project/luckybooky/domain/user/entity/Step1Question.java
- src/main/java/project/luckybooky/domain/user/entity/Step2Question.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/entity/UserType.java
- src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/domain/user/service/UserTypeService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- #16 
- 사용자 유형 검사
- 유저 테이블 컬럼 추가 (phone_num, user_type, gruop_type)
> [FEAT] 사용자 유형 검사 + 유저 테이블 컬럼 추가

- docker-compose.yml
> [INIT] #19: 레디스 사용을 위한 도커 세팅

- build.gradle
- docker-compose.yml
- src/main/java/project/luckybooky/domain/certification/Service/SmsService.java
- src/main/java/project/luckybooky/domain/certification/controller/SmsController.java
- src/main/java/project/luckybooky/domain/certification/dto/request/SmsRequestDTO.java
- src/main/java/project/luckybooky/domain/certification/dto/request/SmsVerifyRequestDTO.java
- src/main/java/project/luckybooky/domain/certification/util/SmsCertificationUtil.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- src/main/java/project/luckybooky/global/redis/RedisSmsCertificationCache.java
- src/main/java/project/luckybooky/global/redis/SmsCertificationCache.java
- #18 
- 인증번호 전송 api
- 인증번호 검증 api
- 레디스 전화번호-인증번호 형식으로 검증
> [FEAT] #18: 인증번호 문자 전송 및 검증 api 구현

- src/main/java/project/luckybooky/domain/location/entity/Location.java
- src/main/java/project/luckybooky/domain/location/entity/type/LocationKeyword.java
- src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
- #26 
- 영화관 정보들을 DB에 저장하였습니다.
> [SETTING] 영화관 리스트 DB 저장

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/entity/Event.java
- src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #29 
- 카테고리별 (최신, 인기, 영화, 드라마, 스포츠, 예능, 콘서트 그 외) 이벤트 목록 조회 API 구현하였습니다.
> [FEATURE] 카테고리별 이벤트 조회 API 구현

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #31 
- 이벤트 상세조회 API 구현하였습니다.
> [FEATURE] 이벤트 상세 조회 API 구현

- src/main/java/project/luckybooky/domain/category/repository/init/CategoryInitializer.java
- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/location/controller/LocationController.java
- src/main/java/project/luckybooky/domain/location/converter/LocationConverter.java
- src/main/java/project/luckybooky/domain/location/dto/request/LocationRequest.java
- src/main/java/project/luckybooky/domain/location/dto/response/LocationResponse.java
- src/main/java/project/luckybooky/domain/location/entity/Location.java
- src/main/java/project/luckybooky/domain/location/entity/type/AvailableMediaType.java
- src/main/java/project/luckybooky/domain/location/repository/LocationRepository.java
- src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
- src/main/java/project/luckybooky/domain/location/service/LocationService.java
- #33 
- 이벤트 생성 시 이벤트 특성에 맞는 영화관 목록 조회 추천 API를 구현하였습니다. 
> [FEATURE] 이벤트 생성 시 이벤트 특성에 맞는 영화관 목록 조회 추천 API 구현

- src/main/java/project/luckybooky/domain/certification/email/service/EmailService.java
- src/main/java/project/luckybooky/domain/certification/sms/Service/SmsService.java
- src/main/java/project/luckybooky/domain/certification/sms/controller/SmsController.java
- src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
- src/main/java/project/luckybooky/domain/user/converter/UserConverter.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserResponseDTO.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/repository/UserRepository.java
- src/main/java/project/luckybooky/domain/user/util/AuthenticatedUserUtils.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/config/SwaggerConfig.java
- #27
- email, sms 인증번호 검증 시 유저 검증
- 이메일 전화번호 저장
- 사용자 유형 검사 결과 조회 api 
> [REFACTOR] email, sms 인증번호 검증 시 유저 검증, 이메일 전화번호 저장, 사용자 유형 검사 결과 조회 api

- src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
- #40 
- 유저 더미데이터 생성 시 createtoken을 통해 토큰 발급(추후 보안 관련 수정 필요)
- dev에서만 실행되도록 세팅
> [refactor] #40: 유저 더미데이터 임시 토큰 발급

- src/main/java/project/luckybooky/global/oauth/util/KakaoUtil.java
> [FIX] 카카오 소셜 로그인 리다이렉트 주소 변경

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/location/converter/LocationConverter.java
- src/main/java/project/luckybooky/domain/location/dto/response/LocationResponse.java
- #35 
- 이벤트 검색 API 구현하였습니다.
- 검색 조건: 이벤트 제목 (전체 제목 혹은 일부도 가능), 카테고리 
> [FEATURE] 이벤트 검색 API 구현

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/entity/Event.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/event/util/EventConstants.java
- src/main/java/project/luckybooky/domain/feedback/controller/FeedbackController.java
- src/main/java/project/luckybooky/domain/feedback/converter/FeedbackConverter.java
- src/main/java/project/luckybooky/domain/feedback/dto/request/FeedbackRequest.java
- src/main/java/project/luckybooky/domain/feedback/dto/response/FeedbackResponse.java
- src/main/java/project/luckybooky/domain/feedback/entity/Feedback.java
- src/main/java/project/luckybooky/domain/feedback/entity/type/NegativeFeedback.java
- src/main/java/project/luckybooky/domain/feedback/entity/type/PositiveFeedback.java
- src/main/java/project/luckybooky/domain/feedback/repository/FeedbackRepository.java
- src/main/java/project/luckybooky/domain/feedback/service/FeedbackService.java
- src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/service/UserTypeService.java
- #45 
- 상영 기간이 지난 이벤트에 대해 상영 완료 처리 & 유저 피드백 수집 기능을 구현하였습니다.
> [FEATURE] 상영 완료 처리 & 사용자 피드백 수집 기능 구현

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/feedback/controller/FeedbackController.java
- src/main/java/project/luckybooky/global/service/UserContextService.java
- #47 
- 컨트롤러에서 로그인한 유저의 유저ID 가져오는 메서드를 별도의 컴포넌트로 분리하였습니다.
> [REFACTOR] 여러 컨트롤러에서 공통적으로 사용되는 메서드(toUserId) -> 별도의 컴포넌트로 분리

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
- src/main/java/project/luckybooky/domain/ticket/converter/TicketConverter.java
- src/main/java/project/luckybooky/domain/ticket/dto/response/TicketResponse.java
- src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- #51 
- 티켓 상세 조회 API 구현하였습니다.
> [FEATURE] 티켓 상세 조회 API 구현 

- src/main/java/project/luckybooky/domain/certification/email/controller/EmailController.java
- src/main/java/project/luckybooky/domain/certification/sms/controller/SmsController.java
- src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/controller/MypageController.java
- src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
- src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
- src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
- src/main/java/project/luckybooky/domain/user/dto/response/ReissueResultDTO.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/domain/user/service/MypageService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtUtil.java
- src/main/java/project/luckybooky/global/jwt/TokenService.java
- #54 
- 마이페이지(유저정보) api 구현
- 토큰 재발급 api 구현
- 리프레쉬 토큰 레디스 캐싱 기능 추가
> [FEAT] 마이페이지 api, 토큰 재발급 api 구현

- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtUtil.java
> [CHORE] #57: 로그인 hotfix

- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtUtil.java
> [CHORE] 로그인 hotfix

- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/global/oauth/util/KakaoUtil.java
- #62 
- 로그인 인가 코드를 받는 주소를 프론트엔드 주소로 변경
> [CHORE] #62: redirectUri 수정

- src/main/java/project/luckybooky/domain/category/repository/init/CategoryInitializer.java
- src/main/java/project/luckybooky/domain/event/repository/init/EventInitializer.java
- src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
- src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
- src/main/java/project/luckybooky/global/util/DummyDataInitForDev.java
- #61 
- 실행 시 dev 환경에서 이벤트 및 참여자 더미데이터 생성하도록 EventInitializer를 생성하였습니다.
> [SETTING] 이벤트 더미데이터 생성

- src/main/java/project/luckybooky/global/oauth/util/CookieUtil.java
> [FIX] setDomain 삭제

- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/entity/type/EventStatus.java
- src/main/java/project/luckybooky/domain/event/repository/init/EventInitializer.java
- src/main/java/project/luckybooky/domain/participation/controller/ParticipationController.java
- src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
- src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
- #70 
- 내가 신청한 혹은 주최한 이벤트 목록 조회 API 구현하였습니다.
> [FEATURE] 내가 신청 혹은 주최한 이벤트 목록 조회 API 구현

- src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
- src/main/java/project/luckybooky/domain/ticket/converter/TicketConverter.java
- src/main/java/project/luckybooky/domain/ticket/dto/response/TicketResponse.java
- src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
- src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
- src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
- #72 
- 티켓 목록 조회 API 구현하였습니다.
> [FEATURE] 티켓 목록 조회 API 구현

- src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
- src/main/java/project/luckybooky/domain/user/converter/UserConverter.java
- src/main/java/project/luckybooky/domain/user/dto/request/UserTypeAssignRequest.java
- src/main/java/project/luckybooky/domain/user/dto/response/UserTypeResultDTO.java
- src/main/java/project/luckybooky/domain/user/entity/ContentCategory.java
- src/main/java/project/luckybooky/domain/user/entity/Step1Question.java
- src/main/java/project/luckybooky/domain/user/entity/Step2Question.java
- src/main/java/project/luckybooky/domain/user/entity/UserType.java
- #69 
- 쿼리스트링으로 되어 있던 방법을 requestBody로 수정
- 사용자 유형 검사 결과 문구 변경 및 줄바꿈 추가
> [REFACTOR] 사용자 유형 검사 requestBody로 수정

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/feedback/controller/FeedbackController.java
- src/main/java/project/luckybooky/domain/location/controller/LocationController.java
- src/main/java/project/luckybooky/domain/participation/controller/ParticipationController.java
- src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
> [CHORE] 응답 포멧 통일

- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/global/config/FcmConfig.java
> [CHORE] 이벤트 대관 확정 로직 수정

- src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
- src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
- src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
- src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/service/MypageService.java
- #90
- 마이페이지 조회 시 유저타입타이틀 조회로 수정
- 사용자 보유 티켓 개수 조회
- 유저타입타이틀 줄바꿈 삭제
> [CHORE] 마이페이지 조회 응답값 수정, 줄바꿈 삭제

- src/main/java/project/luckybooky/global/config/SecurityConfig.java
> [CHORE] 사용자 401 오류 해결

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #104
- 카테고리별 이벤트 조회 시 전체 페이지 수도 포함시켰습니다. 
> [REFACTOR] 이벤트 카테고리별 목록 조회 시 총 페이지 수 데이터 추가

- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #107 
- 사용자 역할 처리 로직 개선 및 참여 안 한 유저에 대해 신청x -> 미참여자로 네이밍 수정하였습니다. 
> [REFACTOR] 사용자 역할 처리 로직 개선 & 미참여자 네이밍 수정

- src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
- src/main/java/project/luckybooky/domain/ticket/converter/TicketConverter.java
- src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
- src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
- src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
- #112 
- '티켓으로 이동' API 생성하였습니다. 
> [FEATURE] '티켓으로 이동' API 생성

- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
- src/main/java/project/luckybooky/domain/notification/event/HostNotificationEvent.java
- src/main/java/project/luckybooky/domain/notification/event/ParticipantNotificationEvent.java
- src/main/java/project/luckybooky/domain/notification/listener/HostNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/listener/ParticipantNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/type/ParticipantNotificationType.java
- src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
- src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
- src/main/java/project/luckybooky/global/config/FcmConfig.java
- #85 
- 참여자용 이벤트 상태별 알림 정책 구현
- 알림 전송 시 eventId 전송
- fcmConfig 초기화 방법 클래스패스 리소스 방식으로 수정(배포시에도 동작하도록)
> [FEAT] 참여자 용 알림 기능 구현

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #120 
- 이벤트 검색 API 응답에 총 페이지 수를 추가하였습니다. 
> [REFACTOR] 이벤트 검색 페이지네이션 응답에 총 페이지 수 추가

- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- #124 
- 이벤트 상세 조회 비로그인 유저도 접근 할 수 있도록 수정 
> [CHORE] 이벤트 상세 조회 비로그인 유저 허용

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- #124 
- 비로그인 전용 이벤트 상세 조회 API를 추가하였습니다. 
> [CHORE] 이벤트 상세 조회 비로그인 유저 접근 허용

- src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
- src/main/java/project/luckybooky/domain/user/repository/UserRepository.java
- src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
- #124 
- 로그인 리다이렉트 수정
- 알림 응답값 포멧 수정
> [CHORE] 로그인 리다이렉트 수정, 알림 응답값 포멧 수정

- src/main/java/project/luckybooky/domain/event/entity/Event.java
- src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- #136 
- 이벤트 신청 최대 인원 검증
- 비관적/낙관적 락 적용
> [REFACTOR] 이벤트 신청 최대 인원 검증, 비관적/낙관적 락 적용

- src/main/java/project/luckybooky/global/config/RedissonConfig.java
> [CHORE] #144: redis 접속 시 비밀번호 설정

- build.gradle
- src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
- src/main/java/project/luckybooky/domain/notification/dto/response/NotificationResponseDTO.java
- src/main/java/project/luckybooky/domain/notification/entity/Notification.java
- src/main/java/project/luckybooky/domain/notification/entity/NotificationStatus.java
- src/main/java/project/luckybooky/domain/notification/job/DeleteNotificationJob.java
- src/main/java/project/luckybooky/domain/notification/listener/HostNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/listener/ParticipantNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/repository/NotificationRepository.java
- src/main/java/project/luckybooky/domain/notification/service/NotificationService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- src/main/java/project/luckybooky/global/config/QuartzSchedulerConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
- #162 
- 알림을 엔티티로 저장
- 로그인한 사용자의 모든 알림을 읽음 여부와 관계없이 최신순으로 조회하는 기능 구현
- 알림 삭제 기능 구현
> [FEATURE] 알림 저장 및 사용자별 알림 목록 조회, 알림 삭제(30일 경과 시 자동 삭제) 기능 구현

- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
- src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
- src/main/java/project/luckybooky/domain/notification/dto/request/NotificationRequestDTO.java
- src/main/java/project/luckybooky/domain/notification/dto/response/NotificationResponseDTO.java
- src/main/java/project/luckybooky/domain/notification/dto/response/SendNotificationResponseDTO.java
- src/main/java/project/luckybooky/domain/notification/entity/NotificationInfo.java
- src/main/java/project/luckybooky/domain/notification/listener/HostNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/listener/ParticipantNotificationListener.java
- src/main/java/project/luckybooky/domain/notification/repository/NotificationRepository.java
- src/main/java/project/luckybooky/domain/notification/service/NotificationService.java
- src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
- #165 
- 알림 테이블에 알림 전송 시 알림 내역이 저장되도록 구현
- 사용자에게 저장되어있는 모든 알림 조회 기능 구현
- 안읽음 -> 읽음으로 읽음 상태 수정하는 api 구현
> [CHORE] 알림 전송 시 알림 테이블에 알림 내역 저장되도록 수정, 알림 조회 

- src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
- src/main/java/project/luckybooky/domain/notification/dto/response/NotificationResponseDTO.java
- src/main/java/project/luckybooky/domain/notification/repository/NotificationRepository.java
- src/main/java/project/luckybooky/domain/notification/service/NotificationService.java
- src/main/java/project/luckybooky/domain/notification/type/HostNotificationType.java
- src/main/java/project/luckybooky/domain/notification/type/ParticipantNotificationType.java
- #167 
- 신규 알림 존재 여부 api 구현
- 알림 조회 응답값 수정
> [FEATURE] 새로운 알림 존재 여부 확인 api 구현, 알림 조회 응답값 수정

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/event/dto/request/EventRequest.java
- src/main/java/project/luckybooky/domain/event/entity/Event.java
- src/main/java/project/luckybooky/domain/event/entity/type/AnonymousButtonState.java
- src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- #158 
**QA에서 파악된 이벤트 신청 & 상태 변경 시 발생할 만한 오류에 대한 리팩토링을 수행하였습니다.**
1. 이벤트 생성 시 인원 관련 최대/최소 범위 추가.
2. 대관 신청 / 취소 시 주최자인지 검증 로직 추가.
3. 익명 사용자용 버튼 상태에 '모집 취소' 상태 추가.
4. 각 이벤트 상태 변환 시 현재 상태 확인 로직 추가.
> [REFACTORING] QA에 따른 리팩토링

- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- src/main/java/project/luckybooky/domain/user/entity/User.java
- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- #171
- 로그아웃 기능 구현 -> 로그아웃 시 쿠키에 액세스, 리프레쉬 토큰 삭제 -> db에 유저정보는 그대로 저장
- 회원탈퇴 기능 구현 -> 회원탈퇴시 유저와 연관된 feedback, notification, participant에 cascade를 remove로 설정하고 유저 삭제 시 전부 삭제되도록 설정하여 회원탈퇴 기능 구현
> [FEATURE] 유저 로그아웃, 회원탈퇴 기능 구현

- src/main/java/project/luckybooky/domain/event/controller/EventController.java
- src/main/java/project/luckybooky/domain/participation/controller/ParticipationController.java
- src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
- #180 
- 내가 주최/신청한 이벤트 목록 조회 시 **모집or신청**인 경우 '`모집 취소`', '`대관 취소`'인 이벤트도 추가하였습니다. 
> [REFACTOR] 내가 주최/신청한 이벤트 목록 조회 로직 수정

- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/user/controller/AuthController.java
- #183 
- 기능 QA에서 나온 개선사항들 반영하였습니다.
- 날짜 표기법 통일 
- 회원 탈퇴 API 에러 관련 스웨거 명세 추가.
> [REFACTOR] 기능 QA 반영 

- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- #185 
-  로그인, 인증번호 발송 앤드포인트 Security 허용
> [FIX] 로그인, 인증번호 발송 앤드포인트 Security 허용

- src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
- src/main/java/project/luckybooky/domain/event/entity/Event.java
- src/main/java/project/luckybooky/domain/event/entity/type/EventStatus.java
- src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
- src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
- #183 
- 이벤트 태그(상태)에 '대관 진행 중' 상태를 추가하였고, 그에 따른 일부 로직 수정하였습니다.
- 이벤트탭 리스트 조회 시 우선순위 기준을 수정하였습니다. 
- 신청/모집 이벤트: 모집중+디데이 > 모집완료 > 모집취소 , 
- 확정 이벤트: 대관확정+디데이 > 대관 진행중+디데이 > 상영확정, 상영취소
> [REFACTOR] 기능 QA 반영 (이벤트탭 리스트 조회 기준 수정, 이벤트 태그 추가)

- src/main/java/project/luckybooky/domain/event/service/EventService.java
- src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
- src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
- src/main/java/project/luckybooky/global/config/SecurityConfig.java
- src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
- src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
- src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/project/luckybooky/global/redis/RedisCertificationCache.java
- #182 
- 마이페이지 조회 시 인증된 메일과 소셜 계정 메일이 같이 조회되도록 응답값 수정
- 알림 타이틀을 컨텐츠 제목으로 수정
- 알림 발송 응답값에 잘 못 전달되던 이벤트 ID 수정
> [FIX] 기능 QA 반영

- src/main/java/project/luckybooky/domain/participation/controller/ParticipantInfoController.java
- src/main/java/project/luckybooky/domain/participation/dto/ParticipantInfoResult.java
- src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
- src/main/java/project/luckybooky/domain/participation/service/ParticipantInfoService.java
- src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
- src/main/resources/templates/participants.html
- #202 
- 대관 확정 메일에서 참여자 정보 확인 페이지 접근 시 주최자만 접근할 수 있도록 보안 설정
> [REFACTOR] 참여자 정보 확인 로직 수정

- src/main/java/project/luckybooky/domain/user/service/AuthService.java
- src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
- src/main/java/project/luckybooky/global/jwt/JwtUtil.java
- #226 
- 재로그인 시 401 에러 수정
- 참여자 정보 확인 링크 관련 오류 수정
> [FIX] 재로그인 시 401 에러 수정

- src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
- src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/project/luckybooky/global/oauth/util/KakaoUtil.java
- #233 
- 개발용 카카오 로그인 redirect uri 주소 수정
> [CHORE] 개발용 서버 로그인 redirect uri 주소 수정

- src/main/resources/templates/venue_confirmed.html
- #244 
- 대관 확정 메일에 eventTitle 부분을 mediaTitle로 수정
> [FIX] #244: eventTitle-> mediaTitle로 수정
